CREATE DATABASE SocialNetwork
GO


USE SocialNetwork
 


--CREATE TABLE Account
--(
--	Id INT PRIMARY KEY IDENTITY,
--	Email VARCHAR(30) UNIQUE NOT NULL,
--	[Password] VARCHAR(30) NOT NULL,
--	ProfileId INT NOT NULL
--)
--
--
--
--CREATE TABLE [Profile]
--(
--	Id INT PRIMARY KEY IDENTITY,
--	[Name] VARCHAR(30)  NOT NULL,
--	Surname VARCHAR(30)  NOT NULL,
--	LastOnline DATETIME2  NOT NULL,
--	PhotoUrl VARCHAR(255)  NOT NULL,
--	AccountId INT NOT NULL 	
--)
--
--
----sozdanie ssilkki
--ALTER TABLE Account
--ADD  FOREIGN KEY(ProfileId) References [Profile](Id) 
--
----sozdanie ssilki
--ALTER TABLE [Profile]
--ADD  FOREIGN KEY(AccountId) References [Account](Id)
--

CREATE TABLE Account
(
	Id INT PRIMARY KEY IDENTITY,
	Email VARCHAR(30) UNIQUE NOT NULL,
	[Password] VARCHAR(30) NOT NULL
)

CREATE TABLE [Profile]
(
	Id INT PRIMARY KEY NOT NULL REFERENCES Account(Id) ON DELETE CASCADE,
	[Name] VARCHAR(30) NOT NULL,
	Surname VARCHAR(30) NOT NULL,
	LastOnline DATETIME2 NOT NULL,
	PhotoUrl VARCHAR(255) NOT NULL,
)

CREATE TABLE Post
(
	Id INT PRIMARY KEY IDENTITY,
	ProfileId INT NULL REFERENCES [Profile](Id) ON DELETE SET NULL,
	[Text] VARCHAR(30) NOT NULL,
	DateCreated DATETIME2 NOT NULL
)

CREATE TABLE PostPhoto
(
	Id INT PRIMARY KEY IDENTITY,
	PostId INT NOT NULL REFERENCES Post(Id) ON DELETE CASCADE,
	PhotoUrl VARCHAR(255) NOT NULL
)

CREATE TABLE Comment
(
	Id INT PRIMARY KEY IDENTITY,
	PostId INT NOT NULL REFERENCES Post(Id) ON DELETE CASCADE,
	ProfileId INT NULL REFERENCES [Profile](Id) ON DELETE SET NULL,
	[Text] VARCHAR(30) NOT NULL,
	DateCreated DATETIME2 NOT NULL,
	ParentCommentId INT REFERENCES Comment(Id) ON DELETE NO ACTION,
	Deleted BIT NOT NULL DEFAULT(0)
)

CREATE TABLE Reaction
(
	Id INT PRIMARY KEY IDENTITY,
	Title VARCHAR(30) NOT NULL
)

CREATE TABLE PostReaction
(
	Id INT PRIMARY KEY IDENTITY,
	PostId INT NOT NULL REFERENCES Post(Id) ON DELETE CASCADE,
	ProfileId INT NULL REFERENCES [Profile](Id) ON DELETE SET NULL,
	ReactionId INT NOT NULL DEFAULT(1) REFERENCES Reaction(Id) ON DELETE SET DEFAULT
)

CREATE TABLE CommentReaction
(
	Id INT PRIMARY KEY IDENTITY,
	CommentId INT REFERENCES Comment(Id) ON DELETE CASCADE,
	ProfileId INT NULL REFERENCES [Profile](Id) ON DELETE SET NULL,
	ReactionId INT NOT NULL DEFAULT(1) REFERENCES Reaction(Id) ON DELETE SET DEFAULT
)

CREATE TABLE RelationStatus
(
	Id INT PRIMARY KEY IDENTITY,
	Title VARCHAR(30) NOT NULL
)

CREATE TABLE ProfileRelation
(
	Id INT PRIMARY KEY IDENTITY,
	FromProfileId INT NULL REFERENCES [Profile](Id) ON DELETE NO ACTION, -- ???
	ToProfileId INT NULL REFERENCES [Profile](Id) ON DELETE NO ACTION, -- ???
	RelationStatusId INT NOT NULL REFERENCES RelationStatus(Id) ON DELETE NO ACTION
)

CREATE TABLE [Group]
(
	Id INT PRIMARY KEY IDENTITY,
	Title VARCHAR(30) NOT NULL,
	DateCreated DATETIME2 NOT NULL,
	IsPersonal BIT NOT NULL DEFAULT(0)
)

CREATE TABLE ProfileGroup
(
	Id INT PRIMARY KEY IDENTITY,
	GroupId INT NOT NULL REFERENCES [Group](Id) ON DELETE CASCADE,
	ProfileId INT NULL REFERENCES [Profile](Id) ON DELETE SET NULL
)

CREATE TABLE [Message]
(
	Id INT PRIMARY KEY IDENTITY,
	GroupId INT NOT NULL REFERENCES [Group](Id) ON DELETE CASCADE,
	ProfileId INT NULL REFERENCES [Profile](Id) ON DELETE SET NULL,
	[Text] VARCHAR(30) NOT NULL,
	DateCreated DATETIME2 NOT NULL
)

INSERT INTO RelationStatus VALUES ('Accepted')
INSERT INTO RelationStatus VALUES ('Denied')
INSERT INTO RelationStatus VALUES ('Pending')

INSERT INTO Reaction VALUES ('Like')
INSERT INTO Reaction VALUES ('Love')
INSERT INTO Reaction VALUES ('Facepalm')